# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- checkout: self
  fetchDepth: 0

- task: GitVersion@5
  inputs:
    runtime: 'full'

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: '**/Servus.Akka.Telegram.csproj'
    versioningScheme: 'byBuildNumber'

- task: NuGetCommand@2
  condition:
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'Nuget Servus.Akka.*'

- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'Dirnei'
    repositoryName: 'Bavaria-Black/servus.akka.telegram'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'userSpecifiedTag'
    tag: '$(GitVersion.NugetVersion)'
    title: 'Release $(GitVersion.NugetVersion)'
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'